### ISSUE TITLE
Missing comma in dist file

### ISSUE THREAD

**Issue by acourtiol** [showdownjs/showdown#155] opened 2015-05-28 11:48 UTC
Hello,

Since the latest releases we are having an issue when we concat all our external libs into our vendors file. This problem is coming from a missing comma in the footer of `dist/showdown.js`.

I already tracked down the issue to your gruntfile: 
- https://github.com/showdownjs/showdown/blob/master/Gruntfile.js#L14

I'll link a pull request to this issue to fix this in the next minutes.

Thank you.

**Comment by acourtiol** [comment] 2015-05-28 13:07
By the way, looking at the [ng-showdown](https://github.com/showdownjs/ng-showdown) repository, I think you're going to have the same problem there.

**Comment by tivie** [comment] 2015-05-28 20:48
Thanks @acourtiol Tested locally seems the issue is fixed with your PR

**Closed** 2015-05-28 20:48 UTC
