### ISSUE TITLE
Highlight.js incorporation?

### ISSUE THREAD

**Issue by jacobcxdev** [showdownjs/showdown#577] opened 2018-08-29 05:27 UTC
Is there a way to get highlight.js code syntax highlighting rendered in code blocks, like on Github or Discord?

For example:

\`\`\`js
if (foo) {
    console.log(bar)
}
\`\`\`

Would be coloured with Javascript syntax colours, as seen below, because I specified js after the first ```.

```js
if (foo) {
    console.log(bar)
}
```

Please note that I am not using Node.js, but rather a js file linked to an HTML file on a Github Pages site, so I do not believe that extensions are possible for me. If I am wrong and there is a way to get extensions to load, I would appreciate you sharing it!

Thanks :)

**Comment by tivie** [comment] 2018-08-29 06:28
Duplicate of #427 #325

**Closed by tivie** 2018-08-29 06:29 UTC
Labels: duplicate

**Comment by tivie** [comment] 2018-08-29 06:30
> Please note that I am not using Node.js, but rather a js file linked to an HTML file on a Github Pages site, so I do not believe that extensions are possible for me.

I don't think that's true at all. Extensions work in the browser and in node, so if you can load Showdown, you can probably load extensions.

**Comment by jacobcxdev** [comment] 2018-08-29 20:02
I could load Showdown, but I don't seem to be able to load extensions like [this](https://github.com/Bloggify/showdown-highlight), which have a 'require()' variable in them. I just get an error that 'require' isn't defined or something.

**Comment by tivie** [comment] 2018-08-30 03:50
@jacobcxdev that particular extension you linked is made exclusively for node because the author is using a non conventional way to load it.

However, it's trivial to refactor it to make it work in the browser (see [fiddle in action](https://jsfiddle.net/tivie/ozhu9ksv/)

```js
showdown.extension('highlight', function () {
	return [{
  	type: "output",
  	filter: function (text, converter, options) {
      var left = "<pre><code\\b[^>]*>",
          right = "</code></pre>",
          flags = "g";
      var replacement = function (wholeMatch, match, left, right) {
      	var lang = (left.match(/class=\"([^ \"]+)/) || [])[1];
        left = left.slice(0, 18) + 'hljs ' + left.slice(18);
        if (lang && hljs.getLanguage(lang)) {
        	return left + hljs.highlight(lang, match).value + right;
				} else {
					return left + hljs.highlightAuto(match).value + right;
				}
			};
      return showdown.helper.replaceRecursiveRegExp(text, replacement, left, right, flags);
    }
  }];
});
```

**Comment by tivie** [comment] 2018-09-15 14:06
---

> ### Donate [![Click here to lend your support to: ShowdownJS website and testing platform and make a donation at paypal.com](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://www.paypal.me/tiviesantos)
>As you know, ShowdownJS is a free library and it will remain free forever. However, maintaining and improving the library costs time and money.
>If you like our work and find our library useful, please donate ~~[through Pledgie](https://pledgie.com/campaigns/35166) or~~ directly [through paypal](https://www.paypal.me/tiviesantos)!! Your contribution will be greatly appreciated and help us continue to develop this awesome library.
