### ISSUE TITLE
[Patch] Add target="_blank" to links

### ISSUE THREAD

**Issue by asbai** [showdownjs/showdown#362] opened 2017-03-16 20:33 UTC
I want all links are opened by a new window, the change is simple:

1. Under function `writeAnchorTag` of `showdown.subParser`:
```js
// ...
    var target = " target=\"_blank\"";
    target = target.replace(showdown.helper.regexes.asteriskAndDash, showdown.helper.escapeCharactersCallback);

    var result = '<a href="' + url + '"' + target;
// ...
```
This is for normal link (`[text](url)` form).

2. Under `replaceLink`:
```js
// ...
    var target = " target=\"_blank\"";
    target = target.replace(showdown.helper.regexes.asteriskAndDash, showdown.helper.escapeCharactersCallback);

    return '<a href="' + link + '"' + target + '>' + lnkTxt + '</a>' + append;
```
This one for simple link.

Of course, it would be nice if there is an option to control it (I'm surprised there isn't already one).
:-)

**Comment by tivie** [comment] 2017-03-18 13:33
Duplicate of #337 #249 #247 #222

**Comment by tivie** [comment] 2017-03-18 13:34
Since this is a feature that's been requested over and over again, I will add this as a feature

**Comment by tivie** [comment] 2017-03-30 23:26
Should be implemented

**Comment by tylerjbainbridge** [comment] 2017-03-31 19:23
I'm also looking for this fix - how can I use this new fix? Do I have to target a certain version? Sorry if this is a stupid question.

**Comment by tivie** [comment] 2017-03-31 20:53
Use develop branch

**Closed** 2017-04-23 01:00 UTC
Labels: Duplicate, Enhancement
