### ISSUE TITLE
showndown doesnt translate correctly ordored list to html.

### ISSUE THREAD

**Issue by be-next-hotdog** [showdownjs/showdown#158] opened 2015-06-03 13:25 UTC
While i was trying to input an ordered list as follow :

1.  some text
2.  some text
3.  some text

showdown would transfer these to an unordered list in html : 

 * some text
 * some text
 * some text

eventually a bug ? Or showdown is not able to differentiate ordered list and unordered list ?

**Comment by tivie** [comment] 2015-06-03 23:33
@be-next-hotdog showdown does indeed support ordered lists. In fact i could not reproduce the bug you described. Can you provide more context?

Heres a working fiddle with showdown parsing correctly a ordered list...
http://jsfiddle.net/7reex9sq/1/

**Comment by be-next-hotdog** [comment] 2015-06-04 08:22
For the test cases : 

Test case 1 : 

* Foo
* Bar
* Baz

1. Foo
2. Bar
3. Baz

Transformation result 1: 

* Foo
* Bar
* Baz
* Foo
* Bar
* Baz

Test case 2 : 

1. Foo
2. Bar
3. Baz

* Foo
* Bar
* Baz

Transformation result 2 :

1. Foo
2. Bar
3. Baz
4. Foo
5. Bar
6. Baz

It seems like that showdown will transform to ordered / unordered list according to the first list element type.  Otherwise caused by definition of markdown syntax ? I couldn't put these 2 kinds of etiquette (star/number) in the same list ? Thx a lot.

**Comment by 8Miles-Mai** [comment] 2015-06-04 11:05
yeap.
But we can do like this:
1. 1
2. 2
3. 3

#like this, add an list separator

+ 1
+ 2
+ 3

**Comment by tivie** [comment] 2015-06-04 12:48
@be-next-hotdog yes, this is a known bug/gotcha/feature (we haven't really decided was that is).

John Gruber's (the markdown creator) lib had this odd behavior. According to the author, it is in fact intended. I doubt it... but we haven't yet decided to "fix" this since we want to adhere to the original spec as much as possible.

As a workaround, you can add any character bewteen the 2 lists (as @8Miles-Mai suggested).

**Comment by tivie** [comment] 2015-06-04 12:49
Duplicate of https://github.com/showdownjs/showdown/issues/142

**Closed by tivie** 2015-06-04 12:49 UTC
Labels: Duplicate

**Comment by be-next-hotdog** [comment] 2015-06-04 13:26
Yepp, I knew this solution before, and we could also type a space to each element as : 

* test
* test
 1. test
 2. test

in this case, the showdown will regard the second ordered list as a sublist. StackEdit follows this rule either, also the github comment tool which we use here.

Thx all the same guys !
