### ISSUE TITLE
Ordered / Unordered list

### ISSUE THREAD

**Issue by MarkPatt89** [showdownjs/showdown#594] opened 2018-10-05 14:19 UTC
I don't seem to be able to use ordered and unordered lists together. If I use an ordered list and then below have an unordered list, when rendered the ordered list takes precedence. The same issue occurs whenever I swap the order, with the list type first used taking precedence.

**Comment by tivie** [comment] 2018-10-06 14:13
Can you please provide a bug report in the format: 
 - input
 - expected
 - actual

[I've just tested in the demo, and it seems to be working as intended](http://demo.showdownjs.com/#/1.%20one%0A%202.%20two%0A%203.%20three%0A%0A%20-%20foo%0A%20-%20bar%0A%20-%20baz)

**Comment by tivie** [comment] 2018-10-18 01:14
@MarkPatt89 Closing as no feedback was produced in 11 days. Feel free to reopen the issue if you have something to add.

**Closed by tivie** 2018-10-18 01:14 UTC
Labels: Invalid
