### ISSUE TITLE
Image bug

### ISSUE THREAD

**Issue by MattixNow** [showdownjs/showdown#575] opened 2018-08-28 19:58 UTC
I get an error when the script is started. Here are the logs and my code js

```log
images.js:66 Uncaught TypeError: title.replace is not a function
    at writeImageTag (images.js:66)
    at String.replace (<anonymous>)
    at images.js:100
    at spanGamut.js:15
    at headers.js:50
    at String.replace (<anonymous>)
    at headers.js:44
    at blockGamut.js:13
    at showdown.Converter.makeHtml (converter.js:323)
    at Object.success (index.js:43)
writeImageTag @ images.js:66
(anonymous) @ images.js:100
(anonymous) @ spanGamut.js:15
(anonymous) @ headers.js:50
(anonymous) @ headers.js:44
(anonymous) @ blockGamut.js:13
makeHtml @ converter.js:323
(anonymous) @ index.js:43
u @ jquery.min.js:2
fireWith @ jquery.min.js:2
k @ jquery.min.js:2
(anonymous) @ jquery.min.js:2
load (async)
send @ jquery.min.js:2
ajax @ jquery.min.js:2
w.(anonymous function) @ jquery.min.js:2
(anonymous) @ index.js:40
res/branding/UsefulTools%20Hero.svg:1 GET file:///C:/Users/mgpro/Documents/Dev/temp/test%20markdown/res/branding/UsefulTools%20Hero.svg 0 ()
Image (async)
(anonymous) @ index.js:7
u @ jquery.min.js:2
fireWith @ jquery.min.js:2
k @ jquery.min.js:2
(anonymous) @ jquery.min.js:2
load (async)
send @ jquery.min.js:2
ajax @ jquery.min.js:2
w.(anonymous function) @ jquery.min.js:2
(anonymous) @ index.js:4

```
```js
$.get("https://raw.githubusercontent.com/MattixNow/usefultools/master/res/topics/OSX.md", function (gh) {
    var target = document.getElementById('renderedOSX'),
        converter = new showdown.Converter();
    target.innerHTML = converter.makeHtml(gh);
    myStr = target.innerHTML;

});
```
[The text i want to convert](https://raw.githubusercontent.com/MattixNow/usefultools/master/res/topics/OSX.md)
😄

**Comment by tivie** [comment] 2018-08-29 03:00
well, the error message is certainly cryptic. That is something I will fix in version 2.0 #576

Regarding your specific issue, I couldn't reproduce it. [see this fiddle, it's working fine](https://jsfiddle.net/tivie/38ugtcn1/)

Also, it works fine in [the demo][demo]

[demo]: http://demo.showdownjs.com/#/%23%20Useful%20Tools%20OSX%20%3A%20%3Cspan%20id%3D%221%22%2F%3E%0A%0A%5B!%5BFogView%20Project%20approved%5D(https%3A%2F%2Fimg.shields.io%2Fbadge%2FFogView%2520Quality-approved-00cc66.svg)%5D(https%3A%2F%2Ffogview.web-edu.fr)%0A%0AListe%20de%20diff%C3%A9rent%20outils%20utiles%20gratuit%20et%20pour%20le%20moins%20accessible%20cr%C3%A9%C3%A9%20par%20%5BMatt%C3%A8o%5D(https%3A%2F%2Fgithub.com%2FMattixNow).

**Comment by tivie** [comment] 2018-09-14 14:57
This issue #585 reports the same issue as you. It should be fixed now in master.

**Closed by tivie** 2018-09-14 14:57 UTC
Labels: bug

**Comment by tivie** [comment] 2018-09-15 14:06
---

> ### Donate [![Click here to lend your support to: ShowdownJS website and testing platform and make a donation at paypal.com](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://www.paypal.me/tiviesantos)
>As you know, ShowdownJS is a free library and it will remain free forever. However, maintaining and improving the library costs time and money.
>If you like our work and find our library useful, please donate ~~[through Pledgie](https://pledgie.com/campaigns/35166) or~~ directly [through paypal](https://www.paypal.me/tiviesantos)!! Your contribution will be greatly appreciated and help us continue to develop this awesome library.
