### ISSUE TITLE
simplifiedAutoLink URLs inside parenthesis followed by another character are not parsed correctly

### ISSUE THREAD

**Issue by jendewalt** [showdownjs/showdown#355] opened 2017-03-09 00:14 UTC
Hi again :)

When a user enters an URL inside of parenthesis and follows that with a character, the html is incorrect (with excludeTrailingPunctuationFromURLs = true). For example, if you enter `Some text… (see http://example.com).` the html output is

```html
<p>Some text… (see <a href="http://example.com)">http://example.com)</a>.</p>
```

The expected output is 

```html
<p>Some text… (see <a href="http://example.com">http://example.com</a>).</p>
```

Thanks and also thanks for resolving the last issue so quickly!

**Comment by tivie** [comment] 2017-03-09 00:25
well, this is a hard one to tackle.
Because this is a valid address `http://example.com/foo)`

http://example.com/foo)

**Comment by tivie** [comment] 2017-09-14 15:13
Minor update: The issue is not forgotten, but I haven't figure out an efficient way of doing this...

I have a partial fix: It trims the url of punctuation marks. Example:

```md
Cool site (see http://example.com).!?;,
```

```html
<p>Cool site (see <a href="http://example.com">http://example.com</a>).!?;,</p>
```

but it fails in this case

```md
For a cool site see http://example.com/(cool_site).
```

```html
<p>For a cool site see <a href="http://example.com">http://example.com/(cool_site</a>).</p>
```

**Comment by rugk** [comment] 2018-07-05 16:21
In https://github.com/showdownjs/showdown/issues/560 I've described how a reasonable compromise may be done: If `(`is mentioned in the URL match `)` at the end as "inside URL", otherwise don't.

**Comment by tivie** [comment] 2018-09-25 03:05
Should be fixed now

**Closed** 2018-09-25 03:10 UTC
Labels: bug, pending
