### ISSUE TITLE
ghMentions does not work with username having dots

### ISSUE THREAD

**Issue by davidsandoz** [showdownjs/showdown#574] opened 2018-08-22 07:50 UTC
### Description
In GitLab, dots are allowed in usernames (unlike in GitHub). When using `ghMentions` with `ghMentionsLink`, if the given username contains a dot, the link is made only with what is before the dot.

### Input
```
@john.doe
```
With the following showdown options:
```
{
    ghMentions: true,
    ghMentionsLink: 'https://gitlab.example.com/{u}',
}
```

### Expected output
```
<a href="https://gitlab.example.com/john.doe>@john.doe</a>
```

### Actual output

```
<a href="https://gitlab.example.com/john>@john</a>.doe
```

**Comment by tivie** [comment] 2018-08-22 14:34
Confirmed

**Comment by tivie** [comment] 2018-09-14 15:01
@davidsandoz do you know which characters are allowed in github usernames?

**Comment by tivie** [comment] 2018-09-14 15:31
Github only allows dashes in the middle of the name.

**Comment by davidsandoz** [comment] 2018-09-14 15:32
@tivie You're right. But I'm using showdown with GitLab.

**Comment by tivie** [comment] 2018-09-14 15:34
I will make showdown allow dashes, underscores and dots in the middle of the username, since that seems a valid usecase scenario

**Comment by tivie** [comment] 2018-09-14 16:04
Should be fixed now

**Closed** 2018-09-14 16:04 UTC

**Comment by davidsandoz** [comment] 2018-09-14 16:54
Awesome, thanks! Do you have an idea when will the next release happen?

**Comment by tivie** [comment] 2018-09-14 18:11
Soonish I hope. Version 2.0-alpha will be the next release.

**Comment by tivie** [comment] 2018-09-15 14:06
---

> ### Donate [![Click here to lend your support to: ShowdownJS website and testing platform and make a donation at paypal.com](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://www.paypal.me/tiviesantos)
>As you know, ShowdownJS is a free library and it will remain free forever. However, maintaining and improving the library costs time and money.
>If you like our work and find our library useful, please donate ~~[through Pledgie](https://pledgie.com/campaigns/35166) or~~ directly [through paypal](https://www.paypal.me/tiviesantos)!! Your contribution will be greatly appreciated and help us continue to develop this awesome library.

**Comment by davidsandoz** [comment] 2018-09-17 06:40
Done 😉
