### ISSUE TITLE
Issue with < and > when attached to a word

### ISSUE THREAD

**Issue by rubenmamo** [showdownjs/showdown#236] opened 2016-02-01 10:00 UTC
Using the below text in markdown

```
There is a missing word <Test> here!
```

shows 

```
There is a missing word here!
```

Shouldn't the < and > be converted to &lt; and &gt; ?

This only happens when the < is attached to the word, so 

```
There is not a missing word < Test > here!
There is not a missing word < Test> here!
There is not a missing word <Test here!
This does not even appear
```

shows as

```
There is not a missing word < Test > here! There is not a missing word < Test> here! There is not a missing word
```

**Comment by tivie** [comment] 2016-02-01 21:00
The following cases behave as expected:

### Case 1

```md
There is not a missing word < Test > here!
```
converts to:
```html
<p>There is not a missing word &lt; Test &gt; here!</p>
```

### Case 2

```md
There is not a missing word <test> here!
```
converts to:
```html
<p>There is not a missing word <test></test> here!</p>
```

------------

The bug lies in in case 3:

### Case 3

```md
There is not a missing word <test here!
```
should be converted to:
```html
<p>There is not a missing word &lt;test here!</p>
```
instead it's being converted into:
```html
<p>There is not a missing word <test here!<p></test></p>
```

**Comment by rubenmamo** [comment] 2016-02-02 09:57
Shouldn't it however only change ```<test>``` to an HTML element only if it is a valid HTML element?

**Comment by tivie** [comment] 2016-02-02 14:36
Html, namely xhtml, allows custom html tags.
Em 02/02/2016 09:57, "Ruben Mamo" <notifications@github.com> escreveu:

**Comment by tivie** [comment] 2016-03-07 00:49
Update: I'm still working on this bug as it's proving a little more difficult to tackle as first expected.

For now, a workaround is to add a space after <`

```md
There is not a missing word < test here!
```

**Comment by rubenmamo** [comment] 2016-03-07 07:56
thanks for the update

**Comment by rubenmamo** [comment] 2016-08-18 11:33
Do you have an update on this?

**Comment by tivie** [comment] 2016-08-19 18:30
Currently, I couldn't find a simple way of fixing this without rewriting the parsing engine. The problem is that the fix slows down the parsing engine too much, since it requires a bunch of lookaheads.

I can't give you a ETA on this, but for now the issue is in "pending" status.

**Comment by tivie** [comment] 2017-02-06 03:31
This issue should be fixed now. Took me a lot of time because I had to rewrite a bit of the parser logic.

Here's how it works now:

### Case 1

``` md
There is not a missing word < Test > here!
```

converts to:

``` html
<p>There is not a missing word &lt; Test &gt; here!</p>
```

### Case 2

``` md
There is not a missing word <test> here!
```

converts to:

``` html
<p>There is not a missing word <test> here!</p>
```

### Case 3

``` md
There is not a missing word test> here!
```

converts to:

``` html
<p>There is not a missing word test&gt; here!</p>
```

### Case 4

``` md
There is not a missing word <test here!
```

converts to:

``` html
<p>There is not a missing word &lt;test here!</p>
```

**Closed** 2017-02-06 07:23 UTC
Labels: Bug, Pending
