### ISSUE TITLE
Live Preview with iframe

### ISSUE THREAD

**Issue by CSUMBmWall** [showdownjs/showdown#592] opened 2018-10-04 16:40 UTC
When using an iframe in a live preview, it reloads every time the input changes and makes the iframe disappear/reappear with every new character.

**Comment by tivie** [comment] 2018-10-04 19:16
It's impossible to know for sure what the problem is since you don't provide any details but,  I can make an educated guess of the situation.

Regardless, **the issue is not caused by showdown** and **it cannot be fixed by changing showdown** because:

 1. Showdown does not use iframes at all so you're including an HTML element directly or using a third party extension.
 2. "Live previews" are... well... live. This usually means the "reparse" all text everytime there's a change in the source text in order to be updated.
 3. The iframe disappearance/reappearance is not caused by showdown but rather by the browser that performs an async request to the page that the iframe points at. If the HTML node is removed/change and then reinserted, the browser need to reload the iframe.

If that is annoying, I recommend making the preview not so live, but rather only update when the user performs an action (like clicking a button).

**Closed by tivie** 2018-10-04 19:16 UTC
Labels: Invalid, help wanted
