### ISSUE TITLE
Support of MathTex

### ISSUE THREAD

**Issue by karnehm** [showdownjs/showdown#524] opened 2018-05-01 09:13 UTC
Is there any possibility or effort to support TexMath?

This would by very interesting by using showdown resp. building on it projects 

Is there any possibility to use the "markdown-it-texmath" Rendering to handle this problem?

Thank You

**Comment by obedm503** [comment] 2018-05-01 23:38
Possible duplicate of #517 

PS: please search for other issues before opening new ones

**Closed** 2018-05-07 17:36 UTC
Labels: duplicate
