### ISSUE TITLE
Hyperlinks with spaces in URLs are not converting properly

### ISSUE THREAD

**Issue by KirkMunro** [showdownjs/showdown#492] opened 2018-01-24 16:48 UTC
I can paste a hyperlink with spaces in the URL into the address bar of my web browser and it opens just fine.

If I try to enter this in markdown:

`[click me](https://mysite.com/document with spaces.html)`

showdown.js is currently rendering this incorrectly, as:

`[click me](<a href="https://mysite.com/document"></a> with spaces.html)`

It should instead be rendering it as:

<a href="https://mysite.com/document with spaces.html">click me</a>

While GitHub has the same issue, I would still like to see it fixed in showdownjs. Please consider updating showdown.js to properly convert URLs contains spaces in markdown into a proper hyperlink.

Note that in modern browsers, such as Firefox Quantum, if I paste a URL containing %20's into the address bar and load that URL, Firefox replaces all of my %20's with spaces. I can also paste a URL containing spaces into Firefox and it loads just fine, so I think this fix is the right way to go.

**Comment by tivie** [comment] 2018-01-27 20:40
dupe of https://github.com/showdownjs/showdown/issues/469

**Closed by tivie** 2018-01-27 20:40 UTC
Labels: duplicate
