### ISSUE TITLE
Attributes of HTML tags and custom HTML tags are Ignored

### ISSUE THREAD

**Issue by Hamcker** [showdownjs/showdown#552] opened 2018-06-10 11:13 UTC
**Description:** Attributes of HTML tags and custom HTML tags are Ignored when parsing to HTML

**Input:** [texts are dummy]
```
This is a simple text surrounding <div id="someId">a div</div> with an id attribute
or this is an <accardion>Accacrdion</accardion> tag which is ignored totally in output.
```

**Expected Output:**
```
This is a simple text surrounding <div _id="someId"_>a div</div> with an id attribute or this is an _<accardion>Accacrdion</accardion>_ tag which is ignored totally in output.
```

**Actual Output:**
```
This is a simple text surrounding <div>a div</div> with an id attribute or this is an tag which is ignored totally in output.
```

**Comment by tivie** [comment] 2018-06-27 18:48
I couldn't reproduce your issue. [In the demo it's working fine][1]. What version are you using?

[1]: http://demo.showdownjs.com/#/This%20is%20a%20simple%20text%20surrounding%20%3Cdiv%20id%3D%22someId%22%3Ea%20div%3C%2Fdiv%3E%20with%20an%20id%20attribute%0Aor%20this%20is%20an%20%3Caccardion%3EAccacrdion%3C%2Faccardion%3E%20tag%20which%20is%20ignored%20totally%20in%20output.

**Comment by tivie** [comment] 2018-08-29 03:02
Closing as no update provided

**Closed by tivie** 2018-08-29 03:02 UTC
Labels: Invalid, could not reproduce
